redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  username: null
  socket_timeout: 5.0
  socket_connect_timeout: 5.0
  health_check_interval: 30
  decode_responses: true

worker:
  id: "worker-001"
  assigned_users: ["user:1", "user:3", "user:5"]
  steal_targets: ["user:2", "user:4", "user:6", "user:7"]
  poll_interval_seconds: 1.0
  task_timeout_seconds: 300.0
  max_concurrent_tasks: 10
  graceful_shutdown_timeout: 30.0

queue:
  stats_prefix: "fq"
  lua_script_cache_size: 100
  max_retry_attempts: 3
  default_task_timeout: 300.0
  default_max_retries: 3
  enable_pipeline_optimization: true
  pipeline_batch_size: 100
  pipeline_timeout: 5.0
  queue_cleanup_interval: 3600
  stats_aggregation_interval: 300
