# Production common configuration  
# This file contains production-specific settings

# Redis connection configuration (production cluster)
redis:
  host: "redis-cluster.prod.example.com"
  port: 6379
  db: 0
  password: "${REDIS_PASSWORD}"  # Will be replaced by environment variable
  username: "fairqueue"
  socket_timeout: 10.0
  socket_connect_timeout: 10.0
  health_check_interval: 60
  decode_responses: true

# Logging configuration (production level)
log_level: "WARNING"
log_format: "%(asctime)s [%(process)d] %(name)s %(levelname)s: %(message)s"

# Queue configuration (production optimized)
stats_prefix: "prod_fq"
lua_script_cache_size: 200
max_retry_attempts: 5
default_task_timeout: 600.0
default_max_retries: 5

# Pipeline settings (production optimized)  
enable_pipeline_optimization: true
pipeline_batch_size: 200
pipeline_timeout: 10.0

# Performance settings (production)
queue_cleanup_interval: 1800  # 30 minutes
stats_aggregation_interval: 60  # 1 minute
